name: Fetch Telegram Configs

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */8 * * *'

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install pyrogram tgcrypto

    - name: Restore session from secret
      run: echo "${{ secrets.PYROGRAM_SESSION_B64 }}" | base64 -d > pyrogram_config_collector.session

    - name: Run config collector
      env:
        API_ID: ${{ secrets.API_ID }}
        API_HASH: ${{ secrets.API_HASH }}
        PYROGRAM_SESSION_B64: ${{ secrets.PYROGRAM_SESSION_B64 }}
      run: python collect_configs.py

    - name: Commit updated configs
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions@users.noreply.github.com"
        git add output/*.txt all_configs.txt
        git commit -m "🔄 Updated configs from Telegram" || echo "No changes"
        git push
