name: Send Telegram Batch

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  send:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install geoip2
      run: pip install geoip2

    - name: Run script to send batch configs
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
      run: python send_configs_batch.py

    - name: Commit updated index
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions@users.noreply.github.com"
        git add last_index.txt
        git commit -m "Update last index after sending batch" || echo "No changes"
        git push
